### ISSUE TITLE
Broken datasource

### ISSUE THREAD

**Issue by sluongng** [Clarity-89/grafana-finnhub#20]
There are 2 issues when I tried to use this for my home setup:

1. The test query for datasource is using `/profile` url, which require a paid subscription. Instead, I suggest using https://finnhub.io/docs/api/company-profile2 which is free

2. When trying to explore data or setup new dashboard, the datasource error out like this
![image](https://user-images.githubusercontent.com/26684313/154836791-8c29cad1-8d72-4ffa-9001-45a1328e7abd.png)

```
TypeError: Cannot read properties of null (reading 'split')

    at input
    at div
    at div
    at http://grafana.pi2.home/public/build/7095.1322a38d8e955d3d27e7.js:641:1000
    at div
    at div
    at p (http://grafana.pi2.home/public/build/7095.1322a38d8e955d3d27e7.js:396:27)
    at form
    at dd (http://grafana.pi2.home/public/build/7095.1322a38d8e955d3d27e7.js:3095:3961)
    at k (http://grafana.pi2.home/public/plugins/clarity89-finnhub-datasource/module.js:2:11453)
    at Sl (http://grafana.pi2.home/public/build/7095.1322a38d8e955d3d27e7.js:2870:458)
    at Tl (http://grafana.pi2.home/public/build/7095.1322a38d8e955d3d27e7.js:2870:1006)
...
```

Which suggests that there is some incompatibility with my grafana version: `Grafana v8.3.4 (a551d74b11)` (fairly recent)

**Comment by Clarity-89** [comment]
Hi @sluongng, thank you for the issue. I haven't updated this datasource to be compatible with Grafana 8 yet, will try to find the time to do it soon.

**Comment by Clarity-89** [comment]
Should be fixed by https://github.com/Clarity-89/grafana-finnhub/pull/21
